[
  {"lib/cluster_murmur/config/configuration_validator.ex", :pattern_match_cov, {248, 7}},
  {"lib/cluster_murmur/config/configuration_validator.ex", :pattern_match_cov, {269, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :call, {96, 25}},
  {"lib/cluster_murmur/config/document_decoder.ex", :no_return, {217, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :pattern_match, {217, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :pattern_match, {219, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :pattern_match, {223, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :pattern_match, {224, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :pattern_match, {225, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :unused_fun, {227, 8}},
  {"lib/cluster_murmur/config/document_decoder.ex", :unused_fun, {258, 8}},
  {"lib/cluster_murmur/config/loader.ex", :pattern_match, {34, 5}},
  {"lib/cluster_murmur/config/loader.ex", :pattern_match, {53, 5}},
  {"lib/cluster_murmur/config/loader.ex", :pattern_match, {63, 5}},
  {"lib/cluster_murmur/config/loader.ex", :pattern_match, {72, 5}},
  {"lib/cluster_murmur/config/loader.ex", :unused_fun, {79, 8}},
  {"lib/cluster_murmur/config/loader.ex", :unused_fun, {97, 8}},
  {"lib/cluster_murmur/config/loader.ex", :unused_fun, {110, 8}},
  {"lib/cluster_murmur/config/loader.ex", :pattern_match, {123, 8}},
  {"lib/cluster_murmur/config/manifest.ex", :pattern_match, {189, 8}},
  {"lib/cluster_murmur/config/manifest.ex", :pattern_match, {191, 8}},
  {"lib/cluster_murmur/config/triggers.ex", :pattern_match_cov, {211, 7}},
  {"lib/cluster_murmur/config/triggers.ex", :pattern_match_cov, {493, 7}},
  {"lib/cluster_murmur/conversations/responder_continuation_planner.ex", :pattern_match_cov,
   {471, 8}},
  {"lib/cluster_murmur/conversations/starter_reply_finisher.ex", :pattern_match_cov, {233, 8}},
  {"lib/cluster_murmur/conversations/validator.ex", :call_without_opaque, {190, 63}},
  {"lib/cluster_murmur/conversations/validator.ex", :call_with_opaque, {191, 48}},
  {"lib/cluster_murmur/conversations/validator.ex", :call_without_opaque, {191, 52}},
  {"lib/cluster_murmur/generation/openai_compatible_request.ex", :pattern_match, 1},
  {"lib/cluster_murmur/generation/responder_message_consumer.ex", :pattern_match_cov, {252, 8}},
  {"lib/cluster_murmur/generation/starter_generator.ex", :pattern_match_cov, {176, 8}},
  {"lib/cluster_murmur/observations/debounce_evaluator.ex", :pattern_match_cov, {42, 7}},
  {"lib/cluster_murmur/observers/mcp_response.ex", :call_without_opaque, {103, 34}},
  {"lib/cluster_murmur/observers/mcp_response.ex", :call_with_opaque, {108, 16}},
  {"lib/cluster_murmur/observers/mcp_response.ex", :call_without_opaque, {148, 34}},
  {"lib/cluster_murmur/observers/mcp_response.ex", :call_with_opaque, {154, 16}},
  {"lib/cluster_murmur/observers/mcp_response.ex", :call_without_opaque, {240, 34}},
  {"lib/cluster_murmur/observers/mcp_response.ex", :call_with_opaque, {243, 16}},
  {"lib/cluster_murmur/observers/poller.ex", :pattern_match_cov, {100, 7}},
  {"lib/cluster_murmur/observers/target_catalog.ex", :call_without_opaque, {69, 34}},
  {"lib/cluster_murmur/observers/target_catalog.ex", :call_with_opaque, {74, 16}},
  {"lib/cluster_murmur/observers/target_catalog.ex", :call_without_opaque, {92, 34}},
  {"lib/cluster_murmur/observers/target_catalog.ex", :call_with_opaque, {97, 16}},
  {"lib/cluster_murmur/persistence/event_dispatch_store.ex", :pattern_match_cov, {305, 8}},
  {"lib/cluster_murmur/persistence/event_dispatch_store.ex", :pattern_match_cov, {320, 8}},
  {"lib/cluster_murmur/persistence/event_trigger_conversation_action_store.ex",
   :pattern_match_cov, {77, 7}},
  {"lib/cluster_murmur/persistence/observation_ingestion_store.ex", :pattern_match_cov, {67, 7}},
  {"lib/cluster_murmur/persistence/schedule_state_store.ex", :call_without_opaque, {221, 34}},
  {"lib/cluster_murmur/persistence/schedule_state_store.ex", :call_with_opaque, {223, 46}},
  {"lib/cluster_murmur/personas/binding_validator.ex", :call_without_opaque, {57, 34}},
  {"lib/cluster_murmur/personas/binding_validator.ex", :call_with_opaque, {58, 46}},
  {"lib/cluster_murmur/personas/responder_candidate_projector.ex", :pattern_match_cov, {317, 8}},
  {"lib/cluster_murmur/personas/responder_selector.ex", :call_without_opaque, {84, 34}},
  {"lib/cluster_murmur/personas/responder_selector.ex", :call_with_opaque, {87, 16}},
  {"lib/cluster_murmur/personas/responder_selector.ex", :pattern_match, {140, 8}},
  {"lib/cluster_murmur/personas/starter_candidate_projector.ex", :pattern_match_cov, {195, 8}},
  {"lib/cluster_murmur/personas/starter_selector.ex", :call_without_opaque, {52, 34}},
  {"lib/cluster_murmur/personas/starter_selector.ex", :call_with_opaque, {55, 16}},
  {"lib/cluster_murmur/personas/starter_selector.ex", :pattern_match_cov, {127, 8}},
  {"lib/cluster_murmur/release.ex", :pattern_match_cov, {165, 7}},
  {"lib/cluster_murmur/runtime/recurring_schedule_initializer.ex", :pattern_match_cov, {147, 8}},
  {"lib/cluster_murmur/runtime/responder_conversation_runner.ex", :pattern_match_cov, {144, 7}},
  {"lib/cluster_murmur/runtime/responder_turn_cycle.ex", :pattern_match_cov, {131, 7}},
  {"lib/cluster_murmur/runtime/responder_turn_cycle.ex", :pattern_match_cov, {210, 7}},
  {"lib/cluster_murmur/runtime/responder_turn_cycle.ex", :pattern_match_cov, {225, 7}},
  {"lib/cluster_murmur/startup.ex", :pattern_match, {40, 5}},
  {"lib/cluster_murmur/startup.ex", :pattern_match, {84, 8}},
  {"lib/cluster_murmur/triggers/authorized_conversation_pipeline_consumer.ex",
   :call_without_opaque, {181, 34}},
  {"lib/cluster_murmur/triggers/authorized_conversation_pipeline_consumer.ex", :call_with_opaque,
   {191, 16}},
  {"lib/cluster_murmur/triggers/authorized_starter_pipeline.ex", :pattern_match_cov, {253, 7}},
  {"lib/cluster_murmur/triggers/authorized_starter_pipeline.ex", :pattern_match_cov, {340, 7}},
  {"lib/cluster_murmur/triggers/authorized_starter_pipeline_consumer.ex", :call_without_opaque,
   {173, 34}},
  {"lib/cluster_murmur/triggers/authorized_starter_pipeline_consumer.ex", :call_with_opaque,
   {182, 16}},
  {"lib/cluster_murmur/triggers/event_dispatch_planner.ex", :pattern_match_cov, {89, 7}},
  {"lib/cluster_murmur/triggers/event_dispatch_planner.ex", :pattern_match_cov, {184, 7}},
  {"lib/cluster_murmur/triggers/event_trigger_batch_authorizer.ex", :pattern_match_cov, {108, 7}},
  {"lib/cluster_murmur/triggers/event_trigger_conversation_planner.ex", :pattern_match_cov,
   {73, 7}},
  {"lib/cluster_murmur/triggers/poll_event_trigger_planner.ex", :pattern_match_cov, {94, 7}},
  {"lib/cluster_murmur/triggers/poll_event_trigger_planner.ex", :call_without_opaque, {168, 23}},
  {"lib/cluster_murmur/triggers/poll_event_trigger_planner.ex", :call_with_opaque, {170, 52}},
  {"lib/cluster_murmur/triggers/schedule_execution_planner.ex", :pattern_match_cov, {168, 8}}
]
