[
  {"lib/cluster_murmur/config/configuration_validator.ex", :pattern_match_cov, {248, 7}},
  {"lib/cluster_murmur/config/configuration_validator.ex", :pattern_match_cov, {269, 8}},
  {"lib/cluster_murmur/config/triggers.ex", :pattern_match_cov, {211, 7}},
  {"lib/cluster_murmur/config/triggers.ex", :pattern_match_cov, {493, 7}},
  {"lib/cluster_murmur/conversations/responder_continuation_planner.ex", :pattern_match_cov,
   {471, 8}},
  {"lib/cluster_murmur/conversations/starter_reply_finisher.ex", :pattern_match_cov, {233, 8}},
  {"lib/cluster_murmur/generation/openai_compatible_request.ex", :pattern_match, 1},
  {"lib/cluster_murmur/generation/responder_message_consumer.ex", :pattern_match_cov, {252, 8}},
  {"lib/cluster_murmur/generation/starter_generator.ex", :pattern_match_cov, {176, 8}},
  {"lib/cluster_murmur/observations/debounce_evaluator.ex", :pattern_match_cov, {42, 7}},
  {"lib/cluster_murmur/observers/poller.ex", :pattern_match_cov, {100, 7}},
  {"lib/cluster_murmur/persistence/event_dispatch_store.ex", :pattern_match_cov, {305, 8}},
  {"lib/cluster_murmur/persistence/event_dispatch_store.ex", :pattern_match_cov, {320, 8}},
  {"lib/cluster_murmur/persistence/event_trigger_conversation_action_store.ex",
   :pattern_match_cov, {77, 7}},
  {"lib/cluster_murmur/persistence/observation_ingestion_store.ex", :pattern_match_cov, {67, 7}},
  {"lib/cluster_murmur/release.ex", :pattern_match_cov, {165, 7}},
  {"lib/cluster_murmur/runtime/recurring_schedule_initializer.ex", :pattern_match_cov, {147, 8}},
  {"lib/cluster_murmur/runtime/responder_conversation_runner.ex", :pattern_match_cov, {144, 7}},
  {"lib/cluster_murmur/runtime/responder_turn_cycle.ex", :pattern_match_cov, {131, 7}},
  {"lib/cluster_murmur/runtime/responder_turn_cycle.ex", :pattern_match_cov, {210, 7}},
  {"lib/cluster_murmur/runtime/responder_turn_cycle.ex", :pattern_match_cov, {225, 7}},
  {"lib/cluster_murmur/triggers/authorized_starter_pipeline.ex", :pattern_match_cov, {253, 7}},
  {"lib/cluster_murmur/triggers/authorized_starter_pipeline.ex", :pattern_match_cov, {340, 7}},
  {"lib/cluster_murmur/triggers/event_dispatch_planner.ex", :pattern_match_cov, {89, 7}},
  {"lib/cluster_murmur/triggers/event_dispatch_planner.ex", :pattern_match_cov, {184, 7}},
  {"lib/cluster_murmur/triggers/event_trigger_batch_authorizer.ex", :pattern_match_cov, {108, 7}},
  {"lib/cluster_murmur/triggers/event_trigger_conversation_planner.ex", :pattern_match_cov,
   {73, 7}},
  {"lib/cluster_murmur/triggers/poll_event_trigger_planner.ex", :pattern_match_cov, {94, 7}},
  {"lib/cluster_murmur/triggers/schedule_execution_planner.ex", :pattern_match_cov, {168, 8}}
]
